import React from "react";

function CarData() {
  const cars = [
    {
      id: 1,
      name: "Toyota Corolla",
      image: "/images/cars/corolla1.jpg",
      pricePerDay: 45,
      year: 2020,
      transmission: "Automatic",
      energy_type: "petrol",
      no_seats: "5",
    },
    {
      id: 2,
      name: "Honda Civic",
      image: "/images/cars/civic1.jpg",
      pricePerDay: 50,
      year: 2021,
      transmission: "Manual",
      energy_type: "Diesel",
      no_seats: "5",
    },
    {
      id: 3,
      name: "Ford Focus",
      image: "/images/cars/focus1.jpg",
      pricePerDay: 48,
      year: 2019,
      transmission: "Automatic",
      energy_type: "Petrol",
      no_seats: "5",
    },
    {
      id: 4,
      name: "Chevrolet Malibu",
      image: "/images/cars/malibu1.jpg",
      pricePerDay: 55,
      year: 2022,
      transmission: "Automatic",
    },
    {
      id: 5,
      name: "Hyundai Elantra",
      image: "/images/cars/elantra1.jpg",
      pricePerDay: 47,
      year: 2020,
      transmission: "Manual",
    },
    {
      id: 6,
      name: "Nissan Altima",
      image: "/images/cars/altima1.jpg",
      pricePerDay: 52,
      year: 2021,
      transmission: "Automatic",
    },
    {
      id: 7,
      name: "Kia Forte",
      image: "/images/cars/forte1.jpg",
      pricePerDay: 43,
      year: 2021,
      transmission: "Manual",
    },
    {
      id: 8,
      name: "Volkswagen Jetta",
      image: "/images/cars/jetta1.jpg",
      pricePerDay: 54,
      year: 2022,
      transmission: "Automatic",
    },
    {
      id: 9,
      name: "Mazda 3",
      image: "/images/cars/mazda3.jpg",
      pricePerDay: 49,
      year: 2019,
      transmission: "Manual",
    },
    {
      id: 10,
      name: "Subaru Impreza",
      image: "/images/cars/impreza1.jpg",
      pricePerDay: 46,
      year: 2020,
      transmission: "Automatic",
    },
    {
      id: 11,
      name: "Toyota Camry",
      image: "/images/cars/camry1.jpg",
      pricePerDay: 60,
      year: 2022,
      transmission: "Automatic",
    },
    {
      id: 12,
      name: "Honda Accord",
      image: "/images/cars/accord1.jpg",
      pricePerDay: 58,
      year: 2021,
      transmission: "Automatic",
    },
    {
      id: 13,
      name: "Ford Fusion",
      image: "/images/cars/fusion1.jpg",
      pricePerDay: 57,
      year: 2020,
      transmission: "Manual",
    },
    {
      id: 14,
      name: "Chevrolet Cruze",
      image: "/images/cars/cruze1.jpg",
      pricePerDay: 44,
      year: 2018,
      transmission: "Manual",
    },
    {
      id: 15,
      name: "Hyundai Sonata",
      image: "/images/cars/sonata1.jpg",
      pricePerDay: 59,
      year: 2022,
      transmission: "Automatic",
    },
    {
      id: 16,
      name: "Nissan Sentra",
      image: "/images/cars/sentra1.jpg",
      pricePerDay: 46,
      year: 2020,
      transmission: "Manual",
    },
    {
      id: 17,
      name: "Kia Optima",
      image: "/images/cars/optima1.jpg",
      pricePerDay: 51,
      year: 2019,
      transmission: "Automatic",
    },
    {
      id: 18,
      name: "Volkswagen Passat",
      image: "/images/cars/passat1.jpg",
      pricePerDay: 55,
      year: 2021,
      transmission: "Automatic",
    },
    {
      id: 19,
      name: "Mazda 6",
      image: "/images/cars/mazda6.jpg",
      pricePerDay: 53,
      year: 2021,
      transmission: "Manual",
    },
    {
      id: 20,
      name: "Subaru Legacy",
      image: "/images/cars/legacy1.jpg",
      pricePerDay: 56,
      year: 2022,
      transmission: "Automatic",
    },
    {
      id: 21,
      name: "Toyota Prius",
      image: "/images/cars/prius1.jpg",
      pricePerDay: 50,
      year: 2020,
      transmission: "Automatic",
    },
    {
      id: 22,
      name: "Honda Insight",
      image: "/images/cars/insight1.jpg",
      pricePerDay: 49,
      year: 2021,
      transmission: "Manual",
    },
    {
      id: 23,
      name: "Ford Fiesta",
      image: "/images/cars/fiesta1.jpg",
      pricePerDay: 42,
      year: 2019,
      transmission: "Manual",
    },
    {
      id: 24,
      name: "Chevrolet Sonic",
      image: "/images/cars/sonic1.jpg",
      pricePerDay: 40,
      year: 2018,
      transmission: "Automatic",
    },
    {
      id: 25,
      name: "Hyundai Accent",
      image: "/images/cars/accent1.jpg",
      pricePerDay: 41,
      year: 2020,
      transmission: "Manual",
    },
    {
      id: 26,
      name: "Nissan Versa",
      image: "/images/cars/versa1.jpg",
      pricePerDay: 43,
      year: 2019,
      transmission: "Automatic",
    },
    {
      id: 27,
      name: "Kia Rio",
      image: "/images/cars/rio1.jpg",
      pricePerDay: 44,
      year: 2021,
      transmission: "Manual",
    },
    {
      id: 28,
      name: "Volkswagen Golf",
      image: "/images/cars/golf1.jpg",
      pricePerDay: 53,
      year: 2022,
      transmission: "Automatic",
    },
    {
      id: 29,
      name: "Mazda CX-3",
      image: "/images/cars/cx3.jpg",
      pricePerDay: 52,
      year: 2021,
      transmission: "Manual",
    },
    {
      id: 30,
      name: "Subaru Crosstrek",
      image: "/images/cars/crosstrek1.jpg",
      pricePerDay: 54,
      year: 2020,
      transmission: "Automatic",
    },
    {
      id: 31,
      name: "Toyota Yaris",
      image: "/images/cars/yaris1.jpg",
      pricePerDay: 39,
      year: 2019,
      transmission: "Manual",
    },
    {
      id: 32,
      name: "Honda Fit",
      image: "/images/cars/fit1.jpg",
      pricePerDay: 38,
      year: 2018,
      transmission: "Automatic",
    },
    {
      id: 33,
      name: "Ford EcoSport",
      image: "/images/cars/ecosport1.jpg",
      pricePerDay: 45,
      year: 2021,
      transmission: "Automatic",
    },
    {
      id: 34,
      name: "Chevrolet Trax",
      image: "/images/cars/trax1.jpg",
      pricePerDay: 47,
      year: 2020,
      transmission: "Manual",
    },
    {
      id: 35,
      name: "Hyundai Venue",
      image: "/images/cars/venue1.jpg",
      pricePerDay: 46,
      year: 2021,
      transmission: "Automatic",
    },
    {
      id: 36,
      name: "Nissan Kicks",
      image: "/images/cars/kicks1.jpg",
      pricePerDay: 48,
      year: 2022,
      transmission: "Manual",
    },
    {
      id: 37,
      name: "Kia Soul",
      image: "/images/cars/soul1.jpg",
      pricePerDay: 49,
      year: 2020,
      transmission: "Automatic",
    },
    {
      id: 38,
      name: "Volkswagen Tiguan",
      image: "/images/cars/tiguan1.jpg",
      pricePerDay: 61,
      year: 2021,
      transmission: "Manual",
    },
    {
      id: 39,
      name: "Mazda CX-5",
      image: "/images/cars/cx5.jpg",
      pricePerDay: 63,
      year: 2022,
      transmission: "Automatic",
    },
    {
      id: 40,
      name: "Subaru Forester",
      image: "/images/cars/forester1.jpg",
      pricePerDay: 60,
      year: 2022,
      transmission: "Manual",
    },
    {
      id: 41,
      name: "Toyota RAV4",
      image: "/images/cars/rav4.jpg",
      pricePerDay: 65,
      year: 2022,
      transmission: "Automatic",
    },
    {
      id: 42,
      name: "Honda CR-V",
      image: "/images/cars/crv.jpg",
      pricePerDay: 64,
      year: 2021,
      transmission: "Manual",
    },
    {
      id: 43,
      name: "Ford Escape",
      image: "/images/cars/escape1.jpg",
      pricePerDay: 66,
      year: 2020,
      transmission: "Automatic",
    },
    {
      id: 44,
      name: "Chevrolet Equinox",
      image: "/images/cars/equinox1.jpg",
      pricePerDay: 67,
      year: 2022,
      transmission: "Manual",
    },
    {
      id: 45,
      name: "Hyundai Tucson",
      image: "/images/cars/tucson1.jpg",
      pricePerDay: 62,
      year: 2022,
      transmission: "Automatic",
    },
    {
      id: 46,
      name: "Nissan Rogue",
      image: "/images/cars/rogue1.jpg",
      pricePerDay: 68,
      year: 2023,
      transmission: "Manual",
    },
    {
      id: 47,
      name: "Kia Sportage",
      image: "/images/cars/sportage1.jpg",
      pricePerDay: 65,
      year: 2023,
      transmission: "Automatic",
    },
    {
      id: 48,
      name: "Volkswagen Atlas",
      image: "/images/cars/atlas1.jpg",
      pricePerDay: 70,
      year: 2022,
      transmission: "Manual",
    },
    {
      id: 49,
      name: "Mazda CX-9",
      image: "/images/cars/cx9.jpg",
      pricePerDay: 72,
      year: 2023,
      transmission: "Automatic",
    },
    {
      id: 50,
      name: "Subaru Ascent",
      image: "/images/cars/ascent1.jpg",
      pricePerDay: 74,
      year: 2023,
      transmission: "Manual",
    },
  ];
}

export default CarData;
