// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUsersPendingVerification(ctx context.Context) ([]GetUsersPendingVerificationRow, error)
	UploadVerificationDocs(ctx context.Context, arg UploadVerificationDocsParams) error
}

var _ Querier = (*Queries)(nil)
