name: Lint React

on:
  push:
    branches: ["CI"]
    paths:
      - "app/**"
  pull_request:
    branches: ["main", "CI"]
    paths:
      - "app/**"

jobs:
  react-lint:
    name: ESLint (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --no-audit --prefer-offline

      - name: Run ESLint
        run: npx eslint .
